### ISSUE TITLE
[BUG] KillAura and config issues

### ISSUE THREAD

**Issue by NoobToolzz** [7GrandDadPGN/VapeForMiniblox#4]
Is there any way to open a GUI or some way to more simply enable modules. I don't want to keep binding to do this.

**Comment by NoobToolzz** [comment]
Nevermind, just dug through and saw the toggle command. Add ChestSteal?

**Comment by Roblox-Thot** [comment]
I think Cheststeal is a thing already, and anti vpn disabler is impossible since they check the IP on the server and not the client

**Comment by NoobToolzz** [comment]
Yeah just checked, ChestSteal does exist. This is now an actual issue, I would hop into any game mode, play for a bit, and then my character would randomly freeze I am unable to move.

**Comment by NoobToolzz** [comment]
More context, this bug is caused by KillAura, if you have it off, you're all good.

**Comment by NoobToolzz** [comment]
KillAura no longer works. Literally doesn't activate at all.

**Comment by RealPacket** [comment]
It works. Please close your issue.

**Comment by RealPacket** [comment]
> KillAura no longer works. Literally doesn't activate at all. Configs no longer save (along with binds), and there are a few modules enabled by default.

It wasn't saving the configs or binds because KillAura was throwing an exception and that broke the saving of configs, just like in Roblox Vape V4.
